// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiR2JMaU-GYb6f-O5GqtP5b7ZU7sh9f5g',
    appId: '1:266274401572:web:0f38ac5702e3ed736ed7b1',
    messagingSenderId: '266274401572',
    projectId: 'digilibv01',
    authDomain: 'digilibv01.firebaseapp.com',
    storageBucket: 'digilibv01.appspot.com',
    measurementId: 'G-XHRWG1H6LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7v0QQDakq2Xdqef5GJU7bwtN-wBJ0CAg',
    appId: '1:266274401572:android:c7ed084af5b41a076ed7b1',
    messagingSenderId: '266274401572',
    projectId: 'digilibv01',
    storageBucket: 'digilibv01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXIF0SCSyxsdIEBqpxRrzvbG4Z9Lpde9E',
    appId: '1:266274401572:ios:8d3b3e060ad33c576ed7b1',
    messagingSenderId: '266274401572',
    projectId: 'digilibv01',
    storageBucket: 'digilibv01.appspot.com',
    iosClientId: '266274401572-4kaslhhjevrefbvlq0an05epqkf3k6na.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDigitalLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXIF0SCSyxsdIEBqpxRrzvbG4Z9Lpde9E',
    appId: '1:266274401572:ios:8d3b3e060ad33c576ed7b1',
    messagingSenderId: '266274401572',
    projectId: 'digilibv01',
    storageBucket: 'digilibv01.appspot.com',
    iosClientId: '266274401572-4kaslhhjevrefbvlq0an05epqkf3k6na.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDigitalLibrary',
  );
}
